# Generated by Django 6.0.5 on 2026-05-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprestamo',
            name='dias_prestamo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudprestamo',
            name='fecha_entrega_programada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
