# Generated by Django 6.0.5 on 2026-05-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_solicitudprestamo_dias_prestamo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprestamo',
            name='fecha_devolucion_estimada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudprestamo',
            name='fecha_entrega_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudprestamo',
            name='observaciones_entrega',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='solicitudprestamo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
