# Generated by Django 6.0.5 on 2026-05-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_solicitudprestamo_aprobado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprestamo',
            name='alerta_vencimiento_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
