# Generated by Django 6.0.5 on 2026-05-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('laptop', 'Laptop'), ('proyector', 'Proyector'), ('tablet', 'Tablet'), ('accesorio', 'Accesorio'), ('otro', 'Otro')], max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('averiado', 'Averiado'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20)),
                ('ubicacion', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
