# Generated by Django 6.0.5 on 2026-05-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_equipo_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('prestado', 'Prestado'), ('averiado', 'Averiado'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20),
        ),
    ]
